AutenticacaoAspNet/Controllers/PerfilController.cs
using AutenticacaoAspNet.Models;
using AutenticacaoAspNet.Utils;
using AutenticacaoAspNet.ViewModels;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;

namespace AutenticacaoAspNet.Controllers
{
    public class PerfilController : Controller
    {
        private UsuariosContext db = new UsuariosContext();

        [Authorize]
        public ActionResult AlterarSenha()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public ActionResult AlterarSenha(AlterarSenhaViewModel viewmodel)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var identity = User.Identity as ClaimsIdentity;
            var login = identity.Claims.FirstOrDefault(c => c.Type == "Login").Value;

            var usuario = db.Usuarios.FirstOrDefault(u => u.Login == login);

            if (Hash.GerarHash(viewmodel.SenhaAtual) != usuario.Senha)
            {
                ModelState.AddModelError("SenhaAtual", "Senha incorreta");
                return View();
            }

            usuario.Senha = Hash.GerarHash(viewmodel.NovaSenha);
            db.Entry(usuario).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();

            TempData["Mensagem"] = "Senha alterada com sucesso";

            return RedirectToAction("Login", "Autenticacao");
        }
    }
}

AutenticacaoAspNet/Controllers/VersionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net.Http;
using System.Net.Http.Headers;
using AutenticacaoAspNet.Models;

namespace AutenticacaoAspNet.Controllers
{
    public class VersionController : Controller
    {
        HttpClient client;
        // GET: Version
        public ActionResult Version()
        {
            return View();
        }

        public String GetValor()
        {
            client = new HttpClient();
            client.BaseAddress = new System.Uri("http://restapiteste10020180609075137.azurewebsites.net");
            client.DefaultRequestHeaders.Accept.Clear();
            client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));


            var response = client.GetAsync("/api/Leituras/2").Result;


            //Random rn = new Random();
            //var teste = rn.Next(0, 50);

            string teste = response.ToString();
            return response.ToString();
           

        }




    }
}

AutenticacaoAspNet/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Mininglab</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("MiningLab", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            @if (User.Identity.IsAuthenticated)
            {
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Download", "Download", "Download")</li>
                    <li>@Html.ActionLink("Monitoramento", "Version", "Version")</li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li>@Html.ActionLink("Alterar senha", "AlterarSenha", "Perfil")</li>
                    <li>@Html.ActionLink("Sair", "Logout", "Autenticacao")</li>
                </ul>
            </div>



            }
            else
            {
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        <li>@Html.ActionLink("Login", "Login", "Autenticacao")</li>
                        <li>@Html.ActionLink("Cadastre-se", "Cadastrar", "Autenticacao")</li>
                    </ul>
                </div>
            }
                </div>
    </div>



    @*<div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">

                <div class="navbar-collapse collapse">

                    <ul class="nav navbar-nav navbar-right">

                        @if (User.Identity.IsAuthenticated)


                        {
                            @Html.ActionLink("MiningLab", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("Download", "Download", "Download")</li>
                            <li>@Html.ActionLink("Monitoramento", "Version", "Version")</li>


                            <li class="dropdown">
                                <ul class="nav navbar-nav ">
                                    <li>@Html.ActionLink("Alterar senha", "AlterarSenha", "Perfil")</li>
                                    <li>@Html.ActionLink("Sair", "Logout", "Autenticacao")</li>
                                </ul>
                            </li>
                        }
                        else
                        {
                            <li>@Html.ActionLink("Login", "Login", "Autenticacao")</li>
                            <li>@Html.ActionLink("Cadastre-se", "Cadastrar", "Autenticacao")</li>
                        }
                    </ul>
                </div>
            </div>
        </div>*@

    <div class="container-fluid">
        @RenderBody()
        <hr />

    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
    @RenderSection("scripts", false)
</body>
</html>